site_name: {{cookiecutter.project_name}}
repo_url: https://{{cookiecutter.git_server}}/{{cookiecutter.author_username}}/{{cookiecutter.project_name}}
site_url: https://{{cookiecutter.author_username}}.github.io/{{cookiecutter.project_name}}
site_description: {{cookiecutter.project_description}}
site_author: {{cookiecutter.author}}
edit_uri: edit/main/docs/
project_name: {{cookiecutter.author_username}}/{{cookiecutter.project_name}}
copyright: Maintained by <a href="https://{{cookiecutter.git_server}}/{{cookiecutter.author_username}}">{{cookiecutter.author_username}}</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [
            "{{cookiecutter.package_name}}"
            ]
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: Chinese
          build: true
  - macros:
      j2_variable_start_string: '[['
      j2_variable_end_string: ']]'

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt

extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: https://{{cookiecutter.git_server}}/{{cookiecutter.author_username}}/{{cookiecutter.project_name}}
  alternate:
    - name: English
      link: en
      lang: en
    - name: Chinese
      link: zh/
      lang: zh
  url:
    prefix: '.'
    videos: /{{cookiecutter.project_name}}

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: underscore
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
